jobs:
  include:
    - stage: Deploy Windows & Mac
      if: tag IS present
      os: osx
      osx_image: xcode11
      script:
        - nvm install 14.7.0
        - nvm use 14.7.0
        - npm install --global yarn
        - yarn install
        - yarn config set version-git-tag false && yarn version --new-version ${TRAVIS_TAG/v/}
        - yarn release --mac --win
