language: node_js
node_js: "14.7.0"

jobs:
  include:
    - stage: Deploy Windows & Mac
      if: tag IS present
      os: osx
      osx_image: xcode11
      script:
        - yarn publish --mac --win
      before_cache:
        - rm -rf $HOME/.cache/electron-builder/wine
    - stage: Deploy Linux
      if: tag IS present
      os: linux
      script:
        - yarn publish

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds
