name: build
on:
  push:
    branches:
      - feature/gha

jobs:
  build_and_sign:
    runs-on: macos-12
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: Get Tag Version
        shell: bash
        run: |
          echo "GITHUB_ACTIONS_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '14.7.0'
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Build and Deploy Windows and Mac
        run: |
          npm install --global yarn \
          yarn install \
          yarn version --new-version ${GITHUB_ACTIONS_TAG/v/} \
          yarn release --mac --win
